### ISSUE TITLE
falscher PIN - Fehler melden 

### ISSUE THREAD

**Issue by ThomasKujawa** [Datenschule/jedeschule.de#39]
Ich habe testweise nach Sachsen gefiltert und es waren außerhalb des Bundes Landes Pins auf der Deutschland - Karte. 

Wo können diese Fehler gemeldet werden? Oder ist das nicht gewünscht? 

https://jedeschule.de/schulen/#!?lat=50.205033264943346&lng=7.42401123046875&zoom=8&state=Sachsen

**Comment by k-nut** [comment]
Die Daten auf der jedeschule.de Seite sind leider schon seit 3 Jahren nicht mehr aktualisiert wurden. Das Problem, das du hier gefunden hast liegt am Geocoding. Wir bekommen von den meisten Bundesländern keine Geokoordinaten sondern fügen diese erst im Nachhinein per geocoding hinzu. Dabei kann es aber immer zu Fehlern kommen. Wir arbeiten aktuell an einer Aktualisierung der Daten bei der wir die Daten dann auch neu geokodieren werden. Das wird aber voraussichtlich leider noch einige Zeit dauern und solange wird die Website fehlerhafte Daten - wie von dir gefunden - anzeigen.

**Comment by ThomasKujawa** [comment]
Das habe ich gar nicht gesehen.

Danke für die Erklärung.
